export const ProductImages = [
  '/public/New folder/plain tshirt.webp',
  '/public/New folder/hoodie.webp',
  '/public/New folder/slimfitjeans.webp',
  '/New folder/leather jacket.webp',
  '/New folder/cookware set.webp',
  '/New folder/makeup.webp',
  '/public/New folder/pan.webp',
  '/New folder/analog watch.webp',
  '/New folder/notebook.webp',
  '/New folder/pen set.webp',
  '/New folder/deskorganier.webp',
  '/New folder/spfThree.webp',
  '/New folder/tent.webp',
  '/New folder/sleeping bag.webp',
  '/New folder/hair dryer.webp',
  '/New folder/shampoo conditioner.webp',
];

export const AllProducts = [
  { 
    id: 1, 
    name: 'Basic T-Shirt', 
    price: 499, 
    image: ProductImages[0], 
    rating: 4, 
    reviews: 120, 
    description: "A simple, comfortable t-shirt made from soft cotton. Ideal for casual wear or layering, offering both comfort and style.", 
    brand: "Brand A", 
    material: "Cotton", 
    size: "L, M, S" 
  },
  { 
    id: 2, 
    name: 'Cotton Hoodie', 
    price: 999, 
    image: ProductImages[1], 
    rating: 5, 
    reviews: 240, 
    description: "A cozy hoodie perfect for chilly weather. Its soft cotton fabric and snug fit make it a must-have for colder seasons.", 
    brand: "Brand B", 
    material: "Cotton", 
    size: "M, L" 
  },
  { 
    id: 3, 
    name: 'Slim Fit Jeans', 
    price: 1299, 
    image: ProductImages[2], 
    rating: 3, 
    reviews: 80, 
    description: "Slim fit jeans that offer a trendy look, with a comfortable stretch to fit your body shape. Perfect for a night out or casual day.", 
    brand: "Brand C", 
    material: "Denim", 
    size: "30, 32, 34" 
  },
  { 
    id: 4, 
    name: 'Leather Jacket', 
    price: 799, 
    image: ProductImages[3], 
    rating: 4, 
    reviews: 190, 
    description: "Stylish leather jacket that adds sophistication to your outfit. Its durable material and sleek design make it suitable for both formal and casual wear.", 
    brand: "Brand D", 
    material: "Leather", 
    size: "M, L" 
  },
  { 
    id: 21, 
    name: 'Cookware Set', 
    price: 2999, 
    image: ProductImages[4], 
    rating: 5, 
    reviews: 350, 
    description: "Complete cookware set for all your cooking needs, with high-quality non-stick coating and durable construction for long-lasting use.", 
    brand: "Brand E", 
    material: "Non-stick Coating", 
    size: "Various sizes" 
  },
  { 
    id: 22, 
    name: 'Makeup Kit', 
    price: 1999, 
    image: ProductImages[5], 
    rating: 4, 
    reviews: 280, 
    description: "Comprehensive makeup kit with all essential tools and shades for a flawless look. Perfect for beginners or makeup enthusiasts.", 
    brand: "Brand F", 
    material: "Varied (Cosmetic Ingredients)", 
    size: "Compact" 
  },
  { 
    id: 23, 
    name: 'Non-stick Frying Pan', 
    price: 1499, 
    image: ProductImages[6], 
    rating: 4, 
    reviews: 150, 
    description: "Non-stick frying pan designed for easy cooking and cleaning. Its ergonomic handle ensures a safe and comfortable cooking experience.", 
    brand: "Brand G", 
    material: "Aluminum with Non-stick Coating", 
    size: "24 cm, 28 cm" 
  },
  { 
    id: 24, 
    name: 'Analog Watch', 
    price: 1299, 
    image: ProductImages[7], 
    rating: 3, 
    reviews: 95, 
    description: "Sleek analog watch with a minimalist design. Its simple and elegant style suits both formal and casual outfits.", 
    brand: "Brand H", 
    material: "Stainless Steel", 
    size: "Standard" 
  },
  { 
    id: 26, 
    name: 'Notebook', 
    price: 199, 
    image: ProductImages[8], 
    rating: 5, 
    reviews: 300, 
    description: "High-quality notebook with smooth pages, perfect for writing, sketching, or note-taking. Ideal for students and professionals alike.", 
    brand: "Brand I", 
    material: "Paper", 
    size: "A4 size" 
  },
  { 
    id: 27, 
    name: 'Pen Set', 
    price: 299, 
    image: ProductImages[9], 
    rating: 4, 
    reviews: 170, 
    description: "A premium pen set with a sleek design and smooth writing experience. A perfect gift or addition to your stationery collection.", 
    brand: "Brand J", 
    material: "Metal, Plastic", 
    size: "Standard Pen Size" 
  },
  { 
    id: 28, 
    name: 'Desk Organizer', 
    price: 999, 
    image: ProductImages[10], 
    rating: 5, 
    reviews: 400, 
    description: "Stylish desk organizer to keep your workspace neat and tidy. It offers compartments for pens, papers, and small office essentials.", 
    brand: "Brand K", 
    material: "Wood and Plastic", 
    size: "30 x 20 x 10 cm" 
  },
  { 
    id: 29, 
    name: 'Headphones', 
    price: 1499, 
    image: ProductImages[11], 
    rating: 4, 
    reviews: 220, 
    description: "High-quality headphones with deep bass and clear sound. Ideal for music lovers and those who enjoy immersive audio experiences.", 
    brand: "Brand L", 
    material: "Plastic, Cushioned", 
    size: "Standard Headphone Size" 
  },
  { 
    id: 31, 
    name: 'Camping Tent', 
    price: 4999, 
    image: ProductImages[12], 
    rating: 5, 
    reviews: 310, 
    description: "Spacious camping tent with waterproof material. Designed for comfort and durability in all types of outdoor environments.", 
    brand: "Brand M", 
    material: "Waterproof Fabric", 
    size: "4 Person Capacity" 
  },
  { 
    id: 32, 
    name: 'Sleeping Bag', 
    price: 1999, 
    image: ProductImages[13], 
    rating: 3, 
    reviews: 110, 
    description: "Warm and comfortable sleeping bag for outdoor adventures. Its compact design makes it easy to pack and carry.", 
    brand: "Brand N", 
    material: "Synthetic Insulation", 
    size: "Standard Sleeping Bag Size" 
  },
  { 
    id: 36, 
    name: 'Hair Dryer', 
    price: 1999, 
    image: ProductImages[14], 
    rating: 4, 
    reviews: 260, 
    description: "Powerful hair dryer with multiple heat settings for fast drying and styling. Compact and easy to use at home or on the go.", 
    brand: "Brand O", 
    material: "Plastic, Electrical Components", 
    size: "Medium Size" 
  },
  { 
    id: 37, 
    name: 'Shampoo Conditioner', 
    price: 799, 
    image: ProductImages[15], 
    rating: 3, 
    reviews: 130, 
    description: "Shampoo and conditioner combo that nourishes and strengthens hair. Designed for daily use with natural ingredients for healthy hair.", 
    brand: "Brand P", 
    material: "Natural Ingredients", 
    size: "250 ml Bottles" 
  },
];
